BBBZ/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BBBZ.Models;

namespace BBBZ.Controllers
{
    public class GroupController : BaseController
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            IsAllowed(MyPermission.Groups); 
        }


        public ActionResult Index()
        {
            return View(SelectableGroup.Convert(FillWithChildren(db.Groups.Where(p => p.Parent == null).ToList())));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Group group = db.Groups.Include(x=>x.Access).Include(x => x.Parent).Include(x=>x.Children).SingleOrDefault(x => x.ID == id);
            
            Group mover = group;
            while (mover != null && mover.Parent != null)
            {
                mover.Parent = db.Groups.Include(x=>x.Parent).SingleOrDefault(x => x.ID == mover.Parent.ID);
                mover = mover.Parent;
            }

            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        public ActionResult Create()
        {
            ViewBag.Groups = SelectableGroup.Convert(FillWithChildren(db.Groups.Where(p => p.Parent == null).ToList()));
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Group group)
        {
            if (ModelState.IsValid)
            {
                group.Parent = db.Groups.SingleOrDefault(x => x.ID == group.helperID);
                group.Permission = new Permission();
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            ViewBag.Groups = SelectableGroup.Convert(FillWithChildren(db.Groups.Where(p => p.Parent == null && p.ID != group.ID).ToList(), group.ID));
            return View(group);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Group group)
        {
            if (ModelState.IsValid)
            {
                var g = db.Groups.Include(x=>x.Parent).SingleOrDefault(x => x.ID == group.ID);
                g.Title = group.Title;
                g.Description = group.Description;

                if (group.helperID == null || group.helperID == -1)
                {
                    if (g.Parent != null)
                        g.Parent.Children.Remove(g);
                }
                else
                    g.Parent = db.Groups.SingleOrDefault(x => x.ID == (int)group.helperID);

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Group group = db.Groups.Include(x => x.Parent).SingleOrDefault(x => x.ID == id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Groups.Include(x=>x.Access).SingleOrDefault(x => x.ID == id);
            DeleteWithChildren(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void DeleteWithChildren(Group grp)
        {
            if (grp == null)
                return;
            var children = db.Groups.Include(x => x.Access).Include(x => x.Parent).Where(x => x.Parent != null && x.Parent.ID == grp.ID).ToList();
            foreach (var c in children)
                DeleteWithChildren(c);
            db.Groups.Remove(grp);
        }



        public ActionResult Setting()
        {
            ViewBag.newUserGroup = SettingManager.NewUserGroupId;
            ViewBag.guestGroup = SettingManager.GuestGroupId;

            return View(GetAllGroups());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Setting(int? newUserGroup, int? guestGroup)
        {
            SettingManager.GuestGroupId = guestGroup;
            SettingManager.NewUserGroupId = newUserGroup;
            return RedirectToAction("Setting");
        }

        public ActionResult Permission(int? id)
        {
            if (id == null)
                return HttpNotFound();
            Permission p =  db.Permissions.SingleOrDefault(x => x.ID == id);
            if (p == null)
            {
                var g = db.Groups.SingleOrDefault(x=>x.ID==id);
                if (g == null)
                    return HttpNotFound();
                else
                {
                    p = new Permission();
                    g.Permission = p;
                    db.SaveChanges();
                }
            }
            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Permission(Permission per)
        {
            if (ModelState.IsValid)
            {
                Permission p = db.Permissions.SingleOrDefault(x => x.ID == per.ID);

                p.Users = per.Users;
                p.Groups = per.Groups;
                p.ViewLevels = per.ViewLevels;
                p.Menus = per.Menus;
                p.Languages = per.Languages;

                p.Media = per.Media;
                p.AdminPanel = per.AdminPanel;

                p.See_Categories = per.See_Categories;
                p.Create_Categories = per.Create_Categories;
                p.Edit_Categories = per.Edit_Categories;
                p.Delete_Categories = per.Delete_Categories;

                p.See_Contents = per.See_Contents;
                p.Create_Contents = per.Create_Contents;
                p.Edit_Contents = per.Edit_Contents;
                p.Delete_Contents = per.Delete_Contents;


                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(per);
        }




        public ActionResult Requests()
        {
            IsAllowed(MyPermission.Groups);

            var req = db.Requests.ToList();
            req.ForEach(z =>
                {
                    z.Access = db.ViewLevels.SingleOrDefault(x => x.ID == z.AccessId);

                    z.Available = db.Groups.Include(x => x.Access)
                        .Where(x => x.Access.Select(q => q.ID).Contains(z.AccessId) == true)
                        .ToList();
                });
            return View(req);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Accept(int? id, bool? accept,int? groupid)
        {
            IsAllowed(MyPermission.Groups);

            if (id == null || accept == null)
                return BadRequest();

            var req = db.Requests.SingleOrDefault(x => x.ID == id);

            if (accept == true)
            {
                if (groupid == null)
                    return BadRequest();

                var g = db.Groups.SingleOrDefault(x => x.ID == groupid);
                if (g == null)
                    return HttpNotFound();

                db.UserGroups.Add(new UserGroup()
                {
                    username = req.Username,
                    Groups = g,
                });
            }

            db.Requests.Remove(req);
            db.SaveChanges();

            return RedirectToAction("Requests");
        }
    }
}

BBBZ/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BBBZ.Models;

namespace BBBZ.Controllers
{
    public class ProfileController : BaseController
    {

        public ActionResult Index(string username)
        {
            if (string.IsNullOrEmpty(username))
                return RedirectToAction("Index", "Home");

            if (username == User.Identity.Name)
                return Edit(username);
            return Details(username);
        }

        private ActionResult Details(string username)
        {
            if (username == null)
                return BadRequest();
            Profile profile = db.Profiles.SingleOrDefault(u => u.username == username);
            if (profile == null)
                return HttpNotFound();
            return View("Details", profile);
        }

        private ActionResult Edit(string username)
        {
            if (username == null)
                return BadRequest();

            if (username != User.Identity.Name)
                return Unauthorized();

            Profile profile = db.Profiles.SingleOrDefault(u => u.username == username);

            if (profile == null)
                return HttpNotFound();

            return View("Edit", profile);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Profile pro)
        {
            if (ModelState.IsValid)
            {
                if (pro.username != User.Identity.Name)
                    return Unauthorized();

                var p = db.Profiles.SingleOrDefault(x => x.username == pro.username);
                p.Name = pro.Name;
                p.LastName = pro.LastName;
                p.Email = pro.Email;
                p.Image = pro.Image;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(pro);
        }
    }
}

BBBZ/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BBBZ.Models;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace BBBZ.Controllers
{
    public class UserController : BaseController
    {
        public UserManager<ApplicationUser> UserManager { get; private set; }
        public UserController()
        {
            UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            IsAllowed(MyPermission.Users);
        }


        public ActionResult Index()
        {
            List<UserManagerDataView> rg = new List<UserManagerDataView>();
            db.Users.ToList().ForEach(x =>
                rg.Add(new UserManagerDataView()
                {
                    TheUser = new RegisterViewModel() { UserName = x.UserName },
                    Locked = x.Locked,
                    AssignedGroups = db.UserGroups.Where(y => y.username == x.UserName).Select(y => y.Groups).ToList()
                }));
            return View(rg);
        }

        public ActionResult Create()
        {
            return View(new UserManagerDataView() { Locked = false, TheUser = null, AllGroups = GetAllGroups() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserManagerDataView us)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser() { UserName = us.TheUser.UserName, Locked = us.Locked };

                var result = UserManager.Create(user, us.TheUser.Password);
                if (result.Succeeded)
                {
                    try
                    {
                        db.Profiles.Add(new Profile()
                        {
                            username = user.UserName,
                            RegisterDate = DateTime.Now,
                            LastVisitDate = DateTime.Now,
                            Image = "/Content/images/user.jpg"
                        });
                        db.SaveChanges();
                    }
                    catch { }

                    foreach (var g in us.AllGroups)
                        if (g.Selected)
                        {
                            var group = db.Groups.SingleOrDefault(x => x.ID == g.ID);

                            if (db.UserGroups.SingleOrDefault(x => x.Groups.ID == group.ID && x.username == user.UserName) == null)
                            {
                                db.UserGroups.Add(new UserGroup() { username = user.UserName, Groups = group });
                                db.SaveChanges();
                            }
                        }

                    
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                        ModelState.AddModelError("", error);
                }
            }

            return View(new UserManagerDataView() { Locked = us.Locked, TheUser = us.TheUser, AllGroups = GetAllGroups() });
        }

        public ActionResult Edit(string username)
        {
            if (string.IsNullOrEmpty(username))
                return RedirectToAction("Index");

            var u = db.Users.SingleOrDefault(x => x.UserName == username);
            var g = db.UserGroups.Where(y => y.username == u.UserName).Select(y => y.Groups).ToList();

            var gs = GetAllGroups();
            gs.ForEach(x => x.Selected = g.SingleOrDefault(z => z.ID == x.ID) != null);

            return View(new UserManagerDataView()
            {
                Locked = u.Locked,
                TheUser = new RegisterViewModel() { UserName = u.UserName },
                AllGroups = gs
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserManagerDataView us)
        {
            var user = db.Users.SingleOrDefault(x => x.UserName == us.TheUser.UserName);
            if (user == null)
                return HttpNotFound();

            user.Locked = us.Locked;

            db.UserGroups.RemoveRange(db.UserGroups.Where(x=>x.username == user.UserName));
            db.SaveChanges();

            foreach (var g in us.AllGroups)
                if (g.Selected)
                {
                    var group = db.Groups.SingleOrDefault(x => x.ID == g.ID);
                    db.UserGroups.Add(new UserGroup() { username = user.UserName, Groups = group });
                }

            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public ActionResult Lock(string username, bool Locked)
        {
            if (ModelState.IsValid)
            {
                var u = db.Users.SingleOrDefault(x => x.UserName == username);
                if (u == null)
                    return HttpNotFound();
                u.Locked = Locked;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && UserManager != null)
            {
                UserManager.Dispose();
                UserManager = null;
            }
            base.Dispose(disposing);
        }
	}
}

BBBZ/Views/User/Create.cshtml
@model BBBZ.Models.UserManagerDataView
@{
    ViewBag.Title = "Create";
    
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "User", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        <div>
            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-xs btn-warning" })
        </div>
        @Html.ValidationSummary(false, null, new { @class = "alert alert-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TheUser.UserName, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.TheUser.UserName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TheUser.UserName, null, new { @class = "has-error" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TheUser.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.TheUser.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TheUser.Password, null, new { @class = "has-error" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TheUser.ConfirmPassword, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.TheUser.ConfirmPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TheUser.ConfirmPassword, null, new { @class = "has-error" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Locked, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Locked, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2">
                User Groups:
                <hr />
                @if (Model != null && Model.AllGroups != null)
                {
                    for (int i = 0 ; i < Model.AllGroups.Count ; i++)
                    {
                        <div>
                            @Html.CheckBoxFor(x => Model.AllGroups[i].Selected, new { @id = "id" + Model.AllGroups[i].ID })
                            @Html.LabelFor(x => Model.AllGroups[i].Selected, Model.AllGroups[i].Text, new { @for = "id" + Model.AllGroups[i].ID })
                            @Html.HiddenFor(x => Model.AllGroups[i].ID)
                        </div>
                    }
                }
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success btn-sm" />
            </div>
        </div>
    </div>
}

BBBZ/Views/User/Edit.cshtml
@model BBBZ.Models.UserManagerDataView
@{
    ViewBag.Title = "Edit";
    
}

<h2>Edit</h2>
@using (Html.BeginForm("Edit", "User", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        <div>
            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-xs btn-warning" })
        </div>
        @Html.ValidationSummary(false, null, new { @class = "alert alert-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TheUser.UserName, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <b><i> @Html.DisplayFor(model => model.TheUser.UserName) </i></b>
                @Html.HiddenFor(model => model.TheUser.UserName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Locked, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Locked, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2">
                User's Groups:
                <hr />
                @if (Model != null && Model.AllGroups != null)
                {
                    for (int i = 0 ; i < Model.AllGroups.Count ; i++)
                    {
                        <div>
                            @Html.CheckBoxFor(x => Model.AllGroups[i].Selected, new { @id = "id" + Model.AllGroups[i].ID })
                            @Html.LabelFor(x => Model.AllGroups[i].Selected, Model.AllGroups[i].Text, new { @for = "id" + Model.AllGroups[i].ID })
                            @Html.HiddenFor(x => Model.AllGroups[i].ID)
                        </div>
                    }
                }
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success btn-sm" />
            </div>
        </div>
    </div>
}

BBBZ/Views/User/Index.cshtml
@model IEnumerable<BBBZ.Models.UserManagerDataView>
@{
    ViewBag.Title = "Users";
    
}

<p>
    <div>
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success btn-sm" })
    </div>
</p>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TheUser.UserName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Locked)
        </th>
        <th>
            Groups
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.TheUser.UserName,"Index", "Profile", new { username = item.TheUser.UserName },null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Locked)
            </td>
            <td>
                @if (item.AssignedGroups == null || item.AssignedGroups.Count == 0)
                {
                    <i> no groups </i>
                }
                else
                {
                    foreach (var g in item.AssignedGroups)
                    {
                        <a href="@Url.Action("Details","Group",new { id = g.ID})"> @g.Title </a> <i>,</i>
                    }
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { username = item.TheUser.UserName }) |
                    @if(item.Locked)
                    {
                        @Html.ActionLink("UnLock", "Lock", new { username = item.TheUser.UserName , Locked = false})
                    }
                    else
                    {
                        @Html.ActionLink("Lock", "Lock", new { username = item.TheUser.UserName, Locked = true })
                    }
            </td>
        </tr>
    }

</table>