BBBZ/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BBBZ.Models;

namespace BBBZ.Controllers
{
    public class GroupController : BaseController
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            IsAllowed(MyPermission.Groups); 
        }


        public ActionResult Index()
        {
            return View(SelectableGroup.Convert(FillWithChildren(db.Groups.Where(p => p.Parent == null).ToList())));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Group group = db.Groups.Include(x=>x.Access).Include(x => x.Parent).Include(x=>x.Children).SingleOrDefault(x => x.ID == id);
            
            Group mover = group;
            while (mover != null && mover.Parent != null)
            {
                mover.Parent = db.Groups.Include(x=>x.Parent).SingleOrDefault(x => x.ID == mover.Parent.ID);
                mover = mover.Parent;
            }

            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        public ActionResult Create()
        {
            ViewBag.Groups = SelectableGroup.Convert(FillWithChildren(db.Groups.Where(p => p.Parent == null).ToList()));
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Group group)
        {
            if (ModelState.IsValid)
            {
                group.Parent = db.Groups.SingleOrDefault(x => x.ID == group.helperID);
                group.Permission = new Permission();
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            ViewBag.Groups = SelectableGroup.Convert(FillWithChildren(db.Groups.Where(p => p.Parent == null && p.ID != group.ID).ToList(), group.ID));
            return View(group);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Group group)
        {
            if (ModelState.IsValid)
            {
                var g = db.Groups.Include(x=>x.Parent).SingleOrDefault(x => x.ID == group.ID);
                g.Title = group.Title;
                g.Description = group.Description;

                if (group.helperID == null || group.helperID == -1)
                {
                    if (g.Parent != null)
                        g.Parent.Children.Remove(g);
                }
                else
                    g.Parent = db.Groups.SingleOrDefault(x => x.ID == (int)group.helperID);

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Group group = db.Groups.Include(x => x.Parent).SingleOrDefault(x => x.ID == id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Groups.Include(x=>x.Access).SingleOrDefault(x => x.ID == id);
            DeleteWithChildren(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void DeleteWithChildren(Group grp)
        {
            if (grp == null)
                return;
            var children = db.Groups.Include(x => x.Access).Include(x => x.Parent).Where(x => x.Parent != null && x.Parent.ID == grp.ID).ToList();
            foreach (var c in children)
                DeleteWithChildren(c);
            db.Groups.Remove(grp);
        }



        public ActionResult Setting()
        {
            ViewBag.newUserGroup = SettingManager.NewUserGroupId;
            ViewBag.guestGroup = SettingManager.GuestGroupId;

            return View(GetAllGroups());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Setting(int? newUserGroup, int? guestGroup)
        {
            SettingManager.GuestGroupId = guestGroup;
            SettingManager.NewUserGroupId = newUserGroup;
            return RedirectToAction("Setting");
        }

        public ActionResult Permission(int? id)
        {
            if (id == null)
                return HttpNotFound();
            Permission p =  db.Permissions.SingleOrDefault(x => x.ID == id);
            if (p == null)
            {
                var g = db.Groups.SingleOrDefault(x=>x.ID==id);
                if (g == null)
                    return HttpNotFound();
                else
                {
                    p = new Permission();
                    g.Permission = p;
                    db.SaveChanges();
                }
            }
            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Permission(Permission per)
        {
            if (ModelState.IsValid)
            {
                Permission p = db.Permissions.SingleOrDefault(x => x.ID == per.ID);

                p.Users = per.Users;
                p.Groups = per.Groups;
                p.ViewLevels = per.ViewLevels;
                p.Menus = per.Menus;
                p.Languages = per.Languages;

                p.Media = per.Media;
                p.AdminPanel = per.AdminPanel;

                p.See_Categories = per.See_Categories;
                p.Create_Categories = per.Create_Categories;
                p.Edit_Categories = per.Edit_Categories;
                p.Delete_Categories = per.Delete_Categories;

                p.See_Contents = per.See_Contents;
                p.Create_Contents = per.Create_Contents;
                p.Edit_Contents = per.Edit_Contents;
                p.Delete_Contents = per.Delete_Contents;


                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(per);
        }




        public ActionResult Requests()
        {
            IsAllowed(MyPermission.Groups);

            var req = db.Requests.ToList();
            req.ForEach(z =>
                {
                    z.Access = db.ViewLevels.SingleOrDefault(x => x.ID == z.AccessId);

                    z.Available = db.Groups.Include(x => x.Access)
                        .Where(x => x.Access.Select(q => q.ID).Contains(z.AccessId) == true)
                        .ToList();
                });
            return View(req);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Accept(int? id, bool? accept,int? groupid)
        {
            IsAllowed(MyPermission.Groups);

            if (id == null || accept == null)
                return BadRequest();

            var req = db.Requests.SingleOrDefault(x => x.ID == id);

            if (accept == true)
            {
                if (groupid == null)
                    return BadRequest();

                var g = db.Groups.SingleOrDefault(x => x.ID == groupid);
                if (g == null)
                    return HttpNotFound();

                db.UserGroups.Add(new UserGroup()
                {
                    username = req.Username,
                    Groups = g,
                });
            }

            db.Requests.Remove(req);
            db.SaveChanges();

            return RedirectToAction("Requests");
        }
    }
}

BBBZ/Controllers/ViewLevelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BBBZ.Models;

namespace BBBZ.Controllers
{
    public class ViewLevelController : BaseController
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            IsAllowed(MyPermission.ViewLevels);
        }

        public List<Group> FillWithChildren(List<Group> gs)
        {
            foreach (var g in gs)
            {
                g.Children = db.Groups.Where(x => x.Parent != null && x.Parent.ID == g.ID).ToList();
                FillWithChildren(g.Children);
            }
            return gs;
        }

        public ActionResult Index()
        {
            return View(db.ViewLevels.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            ViewLevel viewlevel = db.ViewLevels.Find(id);
            if (viewlevel == null)
            {
                return HttpNotFound();
            }
            viewlevel.Groups = db.Groups.Where(x => x.Access.FirstOrDefault(y => y.ID == viewlevel.ID) != null).ToList();
            return View(viewlevel);
        }
        
        public ActionResult Create()
        {
            return View(new ViewLevelViewModel().Initialize(FillWithChildren(db.Groups.Where(x=>x.Parent == null).ToList())));
        }

        [HttpPost]
        public ActionResult Create(ViewLevelViewModel vl)
        {
            if (ModelState.IsValid)
            {
                db.ViewLevels.Add(AssignTheSelectedGroupsToTheViewLevelAndReturnIt(vl.theViewlevel,vl.Groups));
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vl);
        }
        public ViewLevel AssignTheSelectedGroupsToTheViewLevelAndReturnIt(ViewLevel vl, List<SelectableGroup> sg)
        {
            foreach (var g in sg)
                if (g.Selected)
                {
                    if (vl.Groups.SingleOrDefault(x => x.ID == g.ID) == null)
                        vl.Groups.Add(db.Groups.SingleOrDefault(y => y.ID == g.ID));
                }
                else
                {
                    if (vl.Groups.SingleOrDefault(x => x.ID == g.ID) != null)
                        vl.Groups.Remove(db.Groups.SingleOrDefault(y => y.ID == g.ID));
                }
            return vl;
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            ViewLevel viewlevel = db.ViewLevels.Find(id);
            if (viewlevel == null)
            {
                return HttpNotFound();
            }
            viewlevel.Groups = db.Groups.Include(x => x.Access).Where(x => x.Access.FirstOrDefault(y => y.ID == viewlevel.ID) != null).ToList();

            return View(new ViewLevelViewModel().Initialize(FillWithChildren(db.Groups.Where(x => x.Parent == null).ToList()), viewlevel));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ViewLevelViewModel vl)
        {
            if (ModelState.IsValid)
            {
                var vll = db.ViewLevels.SingleOrDefault(x => x.ID == vl.theViewlevel.ID);
                vll.Title = vl.theViewlevel.Title;
                vll.Description = vl.theViewlevel.Description;
                vll.Groups = db.Groups.Include(x=>x.Access).Where(x => x.Access.FirstOrDefault(y => y.ID == vll.ID) != null).ToList();

                AssignTheSelectedGroupsToTheViewLevelAndReturnIt(vll, vl.Groups);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vl);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return BadRequest();
            ViewLevel viewlevel = db.ViewLevels.Find(id);
            if (viewlevel == null)
                return HttpNotFound();
            viewlevel.Groups = db.Groups.Include(x => x.Access).Where(x => x.Access.FirstOrDefault(y => y.ID == viewlevel.ID) != null).ToList();
            return View(viewlevel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ViewLevel viewlevel = db.ViewLevels.Include(x=>x.Groups).SingleOrDefault(x => x.ID == id);

            if (viewlevel == null)
                return HttpNotFound();

            db.Contents.Include(x => x.Access)
                .Where(x => x.Access != null && x.Access.ID == id).ToList()
                .ForEach(x => x.Access = null);

            db.Categories.Include(x => x.Access)
                .Where(x => x.Access != null && x.Access.ID == id).ToList()
                .ForEach(x => x.Access = null);

            db.Menus.Include(x => x.Access)
                .Where(x => x.Access != null && x.Access.ID == id).ToList()
                .ForEach(x => x.Access = null);


            db.ViewLevels.Remove(viewlevel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BBBZ/Views/ViewLevel/Create.cshtml
@model BBBZ.Models.ViewLevelViewModel

@{
    ViewBag.Title = "Create";
    
}

<h2>Create</h2>

@using (Html.BeginForm("Create","ViewLevel",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>View Level</h4>
        <hr />
		<div>
			@Html.ActionLink("Back", "Index", null, new { @class="btn btn-xs btn-warning"})
            <input type="submit" value="Create" class="btn btn-success btn-xs" />
            <hr />
		</div>
        @Html.ValidationSummary(false, null, new { @class = "alert alert-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.theViewlevel.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.theViewlevel.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.theViewlevel.Title, null, new { @class = "has-error" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.theViewlevel.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.theViewlevel.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.theViewlevel.Description, null, new { @class = "has-error" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2">
                User Groups Having Viewing Access:
                <hr />
                @if (Model != null && Model.Groups != null) 
                {     
                    for (int i = 0 ; i < Model.Groups.Count ; i++)
                    {
                        <div>
                            @Html.CheckBoxFor(x=> Model.Groups[i].Selected, new { @id = "id"+ Model.Groups[i].ID})
                            @Html.LabelFor(x => Model.Groups[i].Selected, Model.Groups[i].Text, new { @for = "id" + Model.Groups[i].ID }) 
                            @Html.HiddenFor(x => Model.Groups[i].ID) 
                        </div>
                    }
                }
            </div>
        </div>
    </div>
}

BBBZ/Views/ViewLevel/Delete.cshtml
@model BBBZ.Models.ViewLevel

@{
    ViewBag.Title = "Delete";
    
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ViewLevel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            Groups
        </dt>

        <dd>
            @if (Model.Groups.Count == 0)
            {
                <i> no any groups </i>
            }
            <ul>
                @foreach (var g in Model.Groups)
                {
                    <li> @g.Title </li>
                }
            </ul>
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-sm" /> |
            @Html.ActionLink("Back", "Index", null, new { @class="btn btn-sm btn-warning"})
        </div>
    }
</div>

BBBZ/Views/ViewLevel/Details.cshtml
@model BBBZ.Models.ViewLevel

@{
    ViewBag.Title = "Details";
    
}

<h2>Details</h2>

<div>
    <h4>ViewLevel</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            Groups
        </dt>

        <dd>
            @if (Model.Groups.Count == 0)
            {
                <i> no any groups </i>
            }
            <ul>
                @foreach (var g in Model.Groups)
                {
                    <li> <a href="@Url.Action("Details","Group", new { id = g.ID})"> @g.Title </a> </li>
                }
            </ul>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class="btn btn-sm btn-success"}) |
    <input type="button" value="Back" class="btn btn-sm btn-warning" onclick="history.go(-1);" />
    @Html.ActionLink("See the List", "Index", null, new { @class = "btn btn-sm btn-warning" })
</p>

BBBZ/Views/ViewLevel/Edit.cshtml
@model BBBZ.Models.ViewLevelViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ViewLevel</h4>
        <hr />
		<div>
			@Html.ActionLink("Back", "Index", null, new { @class="btn btn-xs btn-warning"})
            <input type="submit" value="Save" class="btn btn-success btn-xs" />
            <hr />
		</div>
        @Html.ValidationSummary(false, null, new { @class = "alert alert-danger" })
        @Html.HiddenFor(model => model.theViewlevel.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.theViewlevel.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.theViewlevel.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.theViewlevel.Title, null, new { @class = "has-error" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.theViewlevel.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.theViewlevel.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.theViewlevel.Description, null, new { @class = "has-error" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2">
                User Groups Having Viewing Access:
                <hr />
                @for (int i = 0 ; i < Model.Groups.Count ; i++)
                {
                    <div>
                        @Html.CheckBoxFor(x => Model.Groups[i].Selected, new { @id = "id" + Model.Groups[i].ID })
                        @Html.LabelFor(x => Model.Groups[i].Selected, Model.Groups[i].Text, new { @for = "id" + Model.Groups[i].ID })
                        @Html.HiddenFor(x => Model.Groups[i].ID)
                    </div>
                }
            </div>
        </div>
    </div>
}

BBBZ/Views/ViewLevel/Index.cshtml
@model IEnumerable<BBBZ.Models.ViewLevel>

@{
    ViewBag.Title = "ViewLevels";
    
}

<h2>Access View Level</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success btn-sm" })
</p>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            <a href="@Url.Action("Details",null,new { id = item.ID})">
                @Html.DisplayFor(modelItem => item.Title)
                </a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>