BBBZ/Controllers/MenuItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BBBZ.Models;

namespace BBBZ.Controllers
{
    public class MenuItemController : BaseController
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            IsAllowed(MyPermission.Menus);
        }

        public ActionResult Index(int? id)
        {
            if (id != null)
            {
                ViewBag.ID = id;
                return View(db.Menus
                    .Include(x => x.MenuType)
                    .Include(x => x.Access)
                    .Where(x => x.MenuType != null && x.MenuType.ID == id)
                    .ToList()
                    .FillWithChildren(db)
                    .ConvertToViewModel());
            }
            return View(db.Menus
                .Include(x => x.MenuType)
                .Include(x => x.Access)
                .Where(x => x.Parent == null)
                .ToList()
                .FillWithChildren(db)
                .ConvertToViewModel());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return BadRequest();
            Menu menu = db.Menus
                .Include(x => x.Access)
                .Include(x => x.MenuType)
                .Include(x => x.Parent)
                .SingleOrDefault(x => x.ID == id);
            if (menu == null)
                return HttpNotFound();
            return View(menu);
        }

        public ActionResult Create(int? selectedMenuTypeID, string itemtype = "")
        {
            MenuItemViewModel model = new MenuItemViewModel();
            model.ItemType = itemtype;
            model.selectedMenuTypeID = selectedMenuTypeID;
            model.AllMenuTypes = db.MenuTypes.ToList();
            model.AlllCategories = GetAllCategories();
            model.AllContents = GetAllContents();
            model.AllViewLevels = GetAllViewLevels();
            model.AllLanguages = db.GetAllLanguages();

            if (selectedMenuTypeID != null)
            {
                model.TheMenuType = db.MenuTypes.SingleOrDefault(x => x.ID == selectedMenuTypeID);
                if (model.TheMenuType != null)
                    model.AllMenus = db.GetAllMenuItems(db.Menus.Where(x => x.MenuType != null && x.MenuType.ID == model.TheMenuType.ID).ToList());
            }
            else
                model.AllMenus = db.GetAllMenuItems();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MenuItemViewModel menu)
        {
            if (ModelState.IsValid)
            {
                Menu m = new Menu(){
                    Type = menu.ItemType,

                    Title = menu.TheMenu.Title,
                    Note = menu.TheMenu.Note,
                    Published = menu.TheMenu.Published,
                    OpenInSameWindow = menu.TheMenu.OpenInSameWindow,
                    Language = menu.TheMenu.Language,

                    CategoryID = menu.selectedCategoryID,
                    ContentID = menu.selectedContentID,
                    Url = menu.TheMenu.Url,
                };

                if (menu.selectedAccessID != null)
                    m.Access = db.ViewLevels.SingleOrDefault(x => x.ID == menu.selectedAccessID);

                if (menu.selectedParentID != null)
                    m.Parent = db.Menus.SingleOrDefault(x => x.ID == menu.selectedParentID);
                else if (menu.selectedMenuTypeID != null)
                    m.MenuType = db.MenuTypes.SingleOrDefault(x => x.ID == menu.selectedMenuTypeID);

                db.Menus.Add(m);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            MenuItemViewModel model = new MenuItemViewModel();
            model.ItemType = menu.ItemType;
            model.selectedMenuTypeID = menu.selectedMenuTypeID;
            model.AllMenuTypes = db.MenuTypes.ToList();
            model.AlllCategories = GetAllCategories();
            model.AllContents = GetAllContents();
            model.AllViewLevels = GetAllViewLevels();
            model.AllLanguages = db.GetAllLanguages();

            return View(model);
        }

        public ActionResult Edit(int? id, int? selectedMenuTypeID, string itemtype = "")
        {
            if (id == null)
                return BadRequest();
            Menu menu = db.Menus.Include(x=>x.Access).Include(x => x.Parent).Include(x => x.MenuType)
                .SingleOrDefault(x => x.ID == id);
            if (menu == null)
                return HttpNotFound();

            MenuItemViewModel model = new MenuItemViewModel();
            model.ItemType = string.IsNullOrEmpty(itemtype) ? menu.Type : itemtype;
            model.AllMenuTypes = db.MenuTypes.ToList();
            model.TheMenu = menu;
            model.selectedAccessID = menu.Access == null ? 0 : menu.Access.ID;
            model.selectedParentID = menu.Parent == null ? null : (int?)menu.Parent.ID;
            model.TheMenuType = menu.MenuType;

            model.selectedContentID = menu.ContentID;
            model.selectedCategoryID = menu.CategoryID;

            model.AlllCategories = GetAllCategories();
            model.AllContents = GetAllContents();
            model.AllViewLevels = GetAllViewLevels();
            model.AllLanguages = db.GetAllLanguages();

            if (selectedMenuTypeID != null && model.TheMenuType != null && model.TheMenuType.ID != selectedMenuTypeID)
            {
                model.selectedMenuTypeID = selectedMenuTypeID;
                model.TheMenuType = db.MenuTypes.SingleOrDefault(x => x.ID == selectedMenuTypeID);
            }

            if (model.TheMenuType != null)
            {
                model.AllMenus = db.GetAllMenuItems(
                    db.Menus.Where(x => x.MenuType != null && x.MenuType.ID == model.TheMenuType.ID).ToList(),
                    (int)id);
                model.selectedMenuTypeID = model.TheMenuType.ID;
            }
            else
            {
                model.selectedMenuTypeID = null;
                model.AllMenus = db.GetAllMenuItems(null, (int)id);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MenuItemViewModel menu)
        {
            if (ModelState.IsValid)
            {
                if (menu.id == menu.selectedParentID)
                    ModelState.AddModelError("", "Parent can't be same item");
                else
                {
                    Menu m = db.Menus
                        .Include(x => x.Access)
                        .Include(x => x.MenuType)
                        .Include(x => x.Parent)
                        .SingleOrDefault(x => x.ID == menu.id);

                    if (m != null)
                    {
                        m.Type = menu.ItemType;

                        m.Title = menu.TheMenu.Title;
                        m.Note = menu.TheMenu.Note;
                        m.Published = menu.TheMenu.Published;
                        m.OpenInSameWindow = menu.TheMenu.OpenInSameWindow;
                        m.Language = menu.TheMenu.Language;

                        m.CategoryID = menu.selectedCategoryID;
                        m.ContentID = menu.selectedContentID;
                        m.Url = menu.TheMenu.Url;

                        if (m.Access == null ||  menu.selectedAccessID != m.Access.ID)
                            m.Access = db.ViewLevels.SingleOrDefault(x => x.ID == menu.selectedAccessID);

                        if (menu.selectedParentID == null)
                            m.Parent = null;
                        else
                        {
                            if (m.Parent == null || (m.Parent != null && m.Parent.ID != menu.selectedParentID))
                                m.Parent = db.Menus.SingleOrDefault(x => x.ID == menu.selectedParentID);
                            m.MenuType = null;
                        }

                        if (m.Parent == null && menu.selectedMenuTypeID != null)
                            if (m.MenuType == null || (m.MenuType != null && m.MenuType.ID != menu.selectedMenuTypeID))
                                m.MenuType = db.MenuTypes.SingleOrDefault(x => x.ID == menu.selectedMenuTypeID);

                        db.Entry(m).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }

            MenuItemViewModel model = new MenuItemViewModel();
            model.ItemType = menu.ItemType;
            model.selectedAccessID = menu.selectedAccessID;
            model.selectedMenuTypeID = menu.selectedMenuTypeID;
            model.AllMenuTypes = db.MenuTypes.ToList();
            model.AlllCategories = GetAllCategories();
            model.AllContents = GetAllContents();
            model.AllViewLevels = GetAllViewLevels();
            model.AllLanguages = db.GetAllLanguages();
            return View(model);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return BadRequest();
            Menu menu = db.Menus.Find(id);
            if (menu == null)
                return HttpNotFound();
            return View(menu);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.Menus.SingleOrDefault(x => x.ID == id);
            if (menu == null)
                return HttpNotFound();

            DeleteWithChildren(menu);
            db.SaveChanges();

BBBZ/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BBBZ.Models;

namespace BBBZ.Controllers
{
    public class MenusController : BaseController
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            IsAllowed(MyPermission.Menus);
        }

        public ActionResult Index()
        {
            return View(db.MenuTypes.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return BadRequest();
            MenuType menutype = db.MenuTypes.Find(id);
            if (menutype == null)
                return HttpNotFound();
            return View(menutype);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MenuType menut)
        {
            if (ModelState.IsValid)
            {
                db.MenuTypes.Add(menut);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(menut);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return BadRequest();
            MenuType menutype = db.MenuTypes.Find(id);
            if (menutype == null)
                return HttpNotFound();
            return View(menutype);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MenuType menut)
        {
            if (ModelState.IsValid)
            {
                var men = db.MenuTypes.SingleOrDefault(x => x.ID == menut.ID);
                if (men == null)
                    return HttpNotFound();

                men.Title= menut.Title;
                men.Description = menut.Description; 
                men.IsTopMenu = menut.IsTopMenu;
                men.Published = menut.Published;

                db.Entry(men).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menut);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return BadRequest();
            MenuType menutype = db.MenuTypes.Find(id);
            if (menutype == null)
                return HttpNotFound();
            return View(menutype);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MenuType menutype = db.MenuTypes.Include(x => x.Menus).SingleOrDefault(x => x.ID == id);
            db.MenuTypes.Remove(menutype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BBBZ/Views/MenuItem/Create.cshtml
@model BBBZ.Models.MenuItemViewModel

@{
    ViewBag.Title = "Create";
    
}

<h2>Create</h2>

<div class="form-horizontal">
    <h4>Menu</h4>
    <hr />
    <div>
        @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-xs btn-warning" })
    </div>

    @Html.ValidationSummary(false, null, new { @class = "alert alert-danger" })


    <div class="form-group">
       @Html.LabelFor(model => model.ItemType, new { @class = "control-label col-md-2" })
       <div class="col-md-6">
            @using (Html.BeginForm("Create", "MenuItem", FormMethod.Get)) 
            { 
                @Html.DropDownListFor(model=>model.ItemType, new SelectList(Extenisons.GetAllMenuTypes()),string.Empty, new { @class = "form-control", onchange = "submit()" })
                @Html.ValidationMessageFor(model => model.ItemType, null, new { @class = "has-error" })
                @Html.HiddenFor(model => model.selectedMenuTypeID)
            }
       </div>
    </div>

    @if (Model.AllMenuTypes != null)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.selectedMenuTypeID, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @using (Html.BeginForm("Create", "MenuItem", FormMethod.Get))
                {
                    @Html.DropDownListFor(model => model.selectedMenuTypeID, new SelectList(Model.AllMenuTypes, "ID", "Title", string.Empty), string.Empty, new { @class = "form-control", onchange = "submit()" })
                    @Html.HiddenFor(model => model.ItemType)
                }
            </div>
        </div>
    }
   
    @using (Html.BeginForm("Create", "MenuItem", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        
        @Html.HiddenFor(model => model.selectedMenuTypeID)
        @Html.HiddenFor(model => model.ItemType)
        @Html.HiddenFor(model => model.TheMenu.Type)
        if((Model.TheMenu.Type = "SinglePage") != ""){}
        
        if (Model.AllMenus != null)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.selectedParentID, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                        @Html.DropDownListFor(model => model.selectedParentID, new SelectList(Model.AllMenus, "ID", "Title", string.Empty), string.Empty, new { @class = "form-control" })
                </div>
            </div>
        }
    
        <div class="form-group">
            @Html.LabelFor(model => model.TheMenu.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.TheMenu.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TheMenu.Title, null, new { @class = "has-error" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TheMenu.Note, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.TheMenu.Note, new { @class = "form-control" })
            </div>
        </div>

        if (string.IsNullOrEmpty(Model.ItemType) == false)
        {
            if (Model.ItemType.ToLower() == "link")
            { 
                <div class="form-group">
                    @Html.LabelFor(model => model.TheMenu.Url, new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.TheMenu.Url, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TheMenu.Url, null, new { @class = "has-error" })
                    </div>
                </div>
            }
            else if (Model.ItemType.ToLower() == "singlepage")
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.selectedContentID, new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.DropDownListFor(model => model.selectedContentID, new SelectList(Model.AllContents, "ID", "Title"), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.selectedContentID, null, new { @class = "has-error" })
                    </div>
                </div>                
            }
            else if (Model.ItemType.ToLower() == "category")
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.selectedCategoryID, new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.DropDownListFor(model => model.selectedCategoryID, new SelectList(Model.AlllCategories, "ID", "Title"), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.selectedCategoryID, null, new { @class = "has-error" })
                    </div>
                </div>
            }
        }


        <div class="form-group">
            @Html.LabelFor(model => model.selectedAccessID, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.selectedAccessID, new SelectList(Model.AllViewLevels, "ID", "Title") ,new { @class = "form-control" })
            </div>
        </div>
                
        
        <div class="form-group">
            @Html.LabelFor(model => model.TheMenu.Language, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.TheMenu.Language, new SelectList(Model.AllLanguages, "Code", "Title", string.Empty), string.Empty, new { @class = "form-control" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.TheMenu.Published, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.TheMenu.Published, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TheMenu.OpenInSameWindow, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.TheMenu.OpenInSameWindow, new { @class = "form-control" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success btn-sm" />
            </div>
        </div>
    }
</div>

BBBZ/Views/MenuItem/Delete.cshtml
@model BBBZ.Models.Menu

@{
    ViewBag.Title = "Delete";
    
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Menu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Published)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Published)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenInSameWindow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenInSameWindow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentID)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Parent)
        </dt>

        <dd>
            @if (Model.Parent == null)
            {
                <i> no parent </i>
            }
            else if (string.IsNullOrEmpty(Model.Parent.Title) == false)
            {
                @Html.ActionLink(Model.Parent.Title, "Details", "MenuItem", new { id = Model.Parent.ID }, null)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuType)
        </dt>

        <dd>
            @if (Model.MenuType == null)
            {
                <i> not selected yet</i>
            }
            else if (string.IsNullOrEmpty(Model.MenuType.Title) == false)
            {
                @Html.ActionLink(Model.MenuType.Title, "Details", "Menus", new { id = Model.MenuType.ID }, null)
            }
        </dd>



        <dt>
            SubMenu
        </dt>

        <dd>
            @if (Model.Children == null)
            {
                <i> no child </i>
            }
            else
            {
                <ul>
                    @foreach (var c in Model.Children)
                    {
                        <li>
                            @Html.ActionLink(c.Title, "Details", "MenuItem", new { id = c.ID }, null)
                        </li>
                    }
                </ul>
            }
        </dd>
    </dl>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-sm" /> |
            @Html.ActionLink("Back", "Index", null, new { @class="btn btn-sm btn-warning"})
        </div>
    }
</div>

BBBZ/Views/MenuItem/Details.cshtml
@model BBBZ.Models.Menu

@{
    ViewBag.Title = "Details";
    
}

<h2>Details</h2>

<div>
    <h4>Menu</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Published)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Published)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenInSameWindow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenInSameWindow)
        </dd>


@if (Model.CategoryID != null)
{ 
        <dt>
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>
    
        <dd>
            <a href="@Url.Action("Details", "Category", new { id = Model.CategoryID })"> @Html.DisplayFor(model => model.CategoryID)  </a>
        </dd>
}

@if (Model.ContentID != null)
{
        <dt>
            @Html.DisplayNameFor(model => model.ContentID)
        </dt>
    
        <dd>
            <a href="@Url.Action("Details", "Contents", new  { id = Model.ContentID})"> @Html.DisplayFor(model => model.ContentID)  </a>
        </dd>
}
        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Parent)
        </dt>

        <dd>
            @if (Model.Parent == null)
            {
                <i> no parent </i>
            }
            else if (string.IsNullOrEmpty(Model.Parent.Title) == false)
            {
                @Html.ActionLink(Model.Parent.Title, "Details", "MenuItem", new { id = Model.Parent.ID }, null)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuType)
        </dt>

        <dd>
            @if (Model.MenuType == null)
            {
                <i> not selected yet</i>
            }
            else if (string.IsNullOrEmpty(Model.MenuType.Title) == false)
            {
                @Html.ActionLink(Model.MenuType.Title, "Details", "Menus", new { id = Model.MenuType.ID }, null)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Access)
        </dt>

        <dd>
            @if(Model.Access != null)
            {
                <a href="@Url.Action("Details","ViewLevel", new { id = Model.Access.ID})"> @Html.DisplayFor(model => model.Access.Title)</a>
            }
        </dd>

        <dt>
            SubMenu
        </dt>

        <dd>
            @if (Model.Children == null)
            {
                <i> no child </i>
            }
            else
            {
                <ul>
                @foreach (var c in Model.Children)
                {
                    <li>
                        @Html.ActionLink(c.Title, "Details", "MenuItem", new { id = c.ID }, null)
                    </li>
                }
                </ul>
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class="btn btn-sm btn-success"}) |
    <input type="button" value="Back" class="btn btn-sm btn-warning" onclick="history.go(-1);" /> |
    @Html.ActionLink("See the List", "Index", null, new { @class="btn btn-sm btn-warning"})
</p>

BBBZ/Views/MenuItem/Index.cshtml
@model IEnumerable<BBBZ.Models.MenuViewModel>

@{
    ViewBag.Title = "Menu Items";
    
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "MenuItem", (ViewBag.ID == null) ? null : new { selectedMenuTypeID = ViewBag.ID }, new { @class = "btn btn-success btn-sm" })
</p>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Menu.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Menu.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Menu.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Menu.Language)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Menu.Published)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Menu.Parent)
        </th>
        <th>
            Menu
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Menu.Access)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Menu.ID)
        </td>
        <td>
            @if (string.IsNullOrEmpty(item.Title) == false)
            {
                @Html.ActionLink(item.Title, "Details", "MenuItem", new { id = item.ID }, null)
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Menu.Type)
        </td>
        <td>
            @if (item.Menu.TheLanguage != null)
            { 
                @Html.DisplayFor(modelItem => item.Menu.TheLanguage.Title)
            }
            else
            {
                <i> all </i>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Menu.Published)
        </td>
        <td>
            @if (item.Menu.Parent == null)
            {
                <i> no parent </i>
            }
            else if (string.IsNullOrEmpty(item.Menu.Parent.Title) == false)
            {
                @Html.ActionLink(item.Menu.Parent.Title, "Details", "MenuItem", new { id = item.Menu.Parent.ID }, null)
            }
        </td>
        <td>
            @if (item.Menu.MenuType == null)
            {
                <i> -- </i>
            }
            else if (string.IsNullOrEmpty(item.Menu.MenuType.Title) == false)
            {
                @Html.ActionLink(item.Menu.MenuType.Title, "Details", "Menus", new { id = item.Menu.MenuType.ID }, null)
            }
        </td>
        <td>
            @if(item.Menu.Access != null)
            {
                <a href="@Url.Action("Details","ViewLevel", new { id= item.Menu.Access.ID})">
                    @Html.DisplayFor(modelItem => item.Menu.Access.Title)
                </a>
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "MenuItem", new { id = item.ID },null) | 
            @Html.ActionLink("Delete", "Delete", "MenuItem", new { id = item.ID },null)
        </td>
    </tr>
}

</table>

BBBZ/Views/MenuItem/Startup.cshtml
@model List<BBBZ.Models.MenuViewModel>
@{
    ViewBag.Title = "Startup Setting";
    
}
<h2>Startup menu item</h2>

@using (Html.BeginForm("SetStartup", "MenuItem", FormMethod.Post))
{
    <div class="col-md-6">
        @Html.DropDownList("id", new SelectList(Model, "ID", "Title", ViewBag.StartupMenuItem), new { @class = "form-control" })
    </div>
    <div class="col-md-2">
        <input type="submit" value="Save" class="btn btn-success" />
     </div>
}