BBBZ/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BBBZ.Models;

using System.Data.Entity;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Newtonsoft.Json;

namespace BBBZ.Controllers
{
    //[Authorize(Roles = "admin")]
    public class AdminController: BaseController
    {
        public ActionResult Index(bool onlyOnce = false)
        {
            IsAllowed(MyPermission.AdminPanel);

            


            if (Session["isAdminLayout"] == null)
                Session["isAdminLayout"] = true;
            else
                Session["isAdminLayout"] = !(Session["isAdminLayout"].ToString() == true.ToString());

            return RedirectToAction("Index", "Home");
        }
    }
}

BBBZ/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BBBZ.Models;

namespace BBBZ.Controllers
{
    public class GroupController : BaseController
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            IsAllowed(MyPermission.Groups); 
        }


        public ActionResult Index()
        {
            return View(SelectableGroup.Convert(FillWithChildren(db.Groups.Where(p => p.Parent == null).ToList())));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Group group = db.Groups.Include(x=>x.Access).Include(x => x.Parent).Include(x=>x.Children).SingleOrDefault(x => x.ID == id);
            
            Group mover = group;
            while (mover != null && mover.Parent != null)
            {
                mover.Parent = db.Groups.Include(x=>x.Parent).SingleOrDefault(x => x.ID == mover.Parent.ID);
                mover = mover.Parent;
            }

            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        public ActionResult Create()
        {
            ViewBag.Groups = SelectableGroup.Convert(FillWithChildren(db.Groups.Where(p => p.Parent == null).ToList()));
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Group group)
        {
            if (ModelState.IsValid)
            {
                group.Parent = db.Groups.SingleOrDefault(x => x.ID == group.helperID);
                group.Permission = new Permission();
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            ViewBag.Groups = SelectableGroup.Convert(FillWithChildren(db.Groups.Where(p => p.Parent == null && p.ID != group.ID).ToList(), group.ID));
            return View(group);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Group group)
        {
            if (ModelState.IsValid)
            {
                var g = db.Groups.Include(x=>x.Parent).SingleOrDefault(x => x.ID == group.ID);
                g.Title = group.Title;
                g.Description = group.Description;

                if (group.helperID == null || group.helperID == -1)
                {
                    if (g.Parent != null)
                        g.Parent.Children.Remove(g);
                }
                else
                    g.Parent = db.Groups.SingleOrDefault(x => x.ID == (int)group.helperID);

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Group group = db.Groups.Include(x => x.Parent).SingleOrDefault(x => x.ID == id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Groups.Include(x=>x.Access).SingleOrDefault(x => x.ID == id);
            DeleteWithChildren(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void DeleteWithChildren(Group grp)
        {
            if (grp == null)
                return;
            var children = db.Groups.Include(x => x.Access).Include(x => x.Parent).Where(x => x.Parent != null && x.Parent.ID == grp.ID).ToList();
            foreach (var c in children)
                DeleteWithChildren(c);
            db.Groups.Remove(grp);
        }



        public ActionResult Setting()
        {
            ViewBag.newUserGroup = SettingManager.NewUserGroupId;
            ViewBag.guestGroup = SettingManager.GuestGroupId;

            return View(GetAllGroups());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Setting(int? newUserGroup, int? guestGroup)
        {
            SettingManager.GuestGroupId = guestGroup;
            SettingManager.NewUserGroupId = newUserGroup;
            return RedirectToAction("Setting");
        }

        public ActionResult Permission(int? id)
        {
            if (id == null)
                return HttpNotFound();
            Permission p =  db.Permissions.SingleOrDefault(x => x.ID == id);
            if (p == null)
            {
                var g = db.Groups.SingleOrDefault(x=>x.ID==id);
                if (g == null)
                    return HttpNotFound();
                else
                {
                    p = new Permission();
                    g.Permission = p;
                    db.SaveChanges();
                }
            }
            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Permission(Permission per)
        {
            if (ModelState.IsValid)
            {
                Permission p = db.Permissions.SingleOrDefault(x => x.ID == per.ID);

                p.Users = per.Users;
                p.Groups = per.Groups;
                p.ViewLevels = per.ViewLevels;
                p.Menus = per.Menus;
                p.Languages = per.Languages;

                p.Media = per.Media;
                p.AdminPanel = per.AdminPanel;

                p.See_Categories = per.See_Categories;
                p.Create_Categories = per.Create_Categories;
                p.Edit_Categories = per.Edit_Categories;
                p.Delete_Categories = per.Delete_Categories;

                p.See_Contents = per.See_Contents;
                p.Create_Contents = per.Create_Contents;
                p.Edit_Contents = per.Edit_Contents;
                p.Delete_Contents = per.Delete_Contents;


                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(per);
        }




        public ActionResult Requests()
        {
            IsAllowed(MyPermission.Groups);

            var req = db.Requests.ToList();
            req.ForEach(z =>
                {
                    z.Access = db.ViewLevels.SingleOrDefault(x => x.ID == z.AccessId);

                    z.Available = db.Groups.Include(x => x.Access)
                        .Where(x => x.Access.Select(q => q.ID).Contains(z.AccessId) == true)
                        .ToList();
                });
            return View(req);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Accept(int? id, bool? accept,int? groupid)
        {
            IsAllowed(MyPermission.Groups);

            if (id == null || accept == null)
                return BadRequest();

            var req = db.Requests.SingleOrDefault(x => x.ID == id);

            if (accept == true)
            {
                if (groupid == null)
                    return BadRequest();

                var g = db.Groups.SingleOrDefault(x => x.ID == groupid);
                if (g == null)
                    return HttpNotFound();

                db.UserGroups.Add(new UserGroup()
                {
                    username = req.Username,
                    Groups = g,
                });
            }

            db.Requests.Remove(req);
            db.SaveChanges();

            return RedirectToAction("Requests");
        }
    }
}

BBBZ/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BBBZ.Models;

namespace BBBZ.Controllers
{
    public class MenusController : BaseController
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            IsAllowed(MyPermission.Menus);
        }

        public ActionResult Index()
        {
            return View(db.MenuTypes.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return BadRequest();
            MenuType menutype = db.MenuTypes.Find(id);
            if (menutype == null)
                return HttpNotFound();
            return View(menutype);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MenuType menut)
        {
            if (ModelState.IsValid)
            {
                db.MenuTypes.Add(menut);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(menut);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return BadRequest();
            MenuType menutype = db.MenuTypes.Find(id);
            if (menutype == null)
                return HttpNotFound();
            return View(menutype);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MenuType menut)
        {
            if (ModelState.IsValid)
            {
                var men = db.MenuTypes.SingleOrDefault(x => x.ID == menut.ID);
                if (men == null)
                    return HttpNotFound();

                men.Title= menut.Title;
                men.Description = menut.Description; 
                men.IsTopMenu = menut.IsTopMenu;
                men.Published = menut.Published;

                db.Entry(men).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menut);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return BadRequest();
            MenuType menutype = db.MenuTypes.Find(id);
            if (menutype == null)
                return HttpNotFound();
            return View(menutype);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MenuType menutype = db.MenuTypes.Include(x => x.Menus).SingleOrDefault(x => x.ID == id);
            db.MenuTypes.Remove(menutype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BBBZ/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BBBZ.Models;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace BBBZ.Controllers
{
    public class UserController : BaseController
    {
        public UserManager<ApplicationUser> UserManager { get; private set; }
        public UserController()
        {
            UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            IsAllowed(MyPermission.Users);
        }


        public ActionResult Index()
        {
            List<UserManagerDataView> rg = new List<UserManagerDataView>();
            db.Users.ToList().ForEach(x =>
                rg.Add(new UserManagerDataView()
                {
                    TheUser = new RegisterViewModel() { UserName = x.UserName },
                    Locked = x.Locked,
                    AssignedGroups = db.UserGroups.Where(y => y.username == x.UserName).Select(y => y.Groups).ToList()
                }));
            return View(rg);
        }

        public ActionResult Create()
        {
            return View(new UserManagerDataView() { Locked = false, TheUser = null, AllGroups = GetAllGroups() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserManagerDataView us)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser() { UserName = us.TheUser.UserName, Locked = us.Locked };

                var result = UserManager.Create(user, us.TheUser.Password);
                if (result.Succeeded)
                {
                    try
                    {
                        db.Profiles.Add(new Profile()
                        {
                            username = user.UserName,
                            RegisterDate = DateTime.Now,
                            LastVisitDate = DateTime.Now,
                            Image = "/Content/images/user.jpg"
                        });
                        db.SaveChanges();
                    }
                    catch { }

                    foreach (var g in us.AllGroups)
                        if (g.Selected)
                        {
                            var group = db.Groups.SingleOrDefault(x => x.ID == g.ID);

                            if (db.UserGroups.SingleOrDefault(x => x.Groups.ID == group.ID && x.username == user.UserName) == null)
                            {
                                db.UserGroups.Add(new UserGroup() { username = user.UserName, Groups = group });
                                db.SaveChanges();
                            }
                        }

                    
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                        ModelState.AddModelError("", error);
                }
            }

            return View(new UserManagerDataView() { Locked = us.Locked, TheUser = us.TheUser, AllGroups = GetAllGroups() });
        }

        public ActionResult Edit(string username)
        {
            if (string.IsNullOrEmpty(username))
                return RedirectToAction("Index");

            var u = db.Users.SingleOrDefault(x => x.UserName == username);
            var g = db.UserGroups.Where(y => y.username == u.UserName).Select(y => y.Groups).ToList();

            var gs = GetAllGroups();
            gs.ForEach(x => x.Selected = g.SingleOrDefault(z => z.ID == x.ID) != null);

            return View(new UserManagerDataView()
            {
                Locked = u.Locked,
                TheUser = new RegisterViewModel() { UserName = u.UserName },
                AllGroups = gs
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserManagerDataView us)
        {
            var user = db.Users.SingleOrDefault(x => x.UserName == us.TheUser.UserName);
            if (user == null)
                return HttpNotFound();

            user.Locked = us.Locked;

            db.UserGroups.RemoveRange(db.UserGroups.Where(x=>x.username == user.UserName));
            db.SaveChanges();

            foreach (var g in us.AllGroups)
                if (g.Selected)
                {
                    var group = db.Groups.SingleOrDefault(x => x.ID == g.ID);
                    db.UserGroups.Add(new UserGroup() { username = user.UserName, Groups = group });
                }

            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public ActionResult Lock(string username, bool Locked)
        {
            if (ModelState.IsValid)
            {
                var u = db.Users.SingleOrDefault(x => x.UserName == username);
                if (u == null)
                    return HttpNotFound();
                u.Locked = Locked;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && UserManager != null)
            {
                UserManager.Dispose();
                UserManager = null;
            }
            base.Dispose(disposing);
        }
	}
}

BBBZ/Views/Shared/_AdminLayout.cshtml
@{
    BBBZ.Models.Permission _perm =(BBBZ.Models.Permission)ViewBag.Permission;
    BBBZ.Models.SharedLayoutViewModel model = ((BBBZ.Models.SharedLayoutViewModel)ViewBag.LayoutViewModel);
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    @Styles.Render("~/Content/admin")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container-fluid container-main">
        @if (model != null)
{
    @Html.Partial("_NavBarPartial", model.TopMenuItems)
}
        <div id="js-cpanel">
 
            <!-- SIDE BAR ---------------------------------------------------------------------------------------->
            <div id="sidebar" class="sidebar">
                <ul class="nav nav-list">
                    @if (_perm.Menus == true)
                    {
                        <li>
                            <a class="dropdown-toggle" href="@Url.Action("Index", "Menus")">
                                <i class="icon-list"></i>
                                <span class="menu-text">  Menu </span>
                                <b class="arrow js-icon-angle-down"></b>
                            </a>
                            <ul class="submenu" style="display:none;">
                                <li>
                                    <a href="@Url.Action("Index", "Menus")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Manage Menus
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "MenuItem")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Manage Menu Items
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create", "MenuItem")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Add Menu Item
                                    </a>
                                </li>

                                <li>
                                    <a href="@Url.Action("Startup", "MenuItem")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Startup Menu Item
                                    </a>
                                </li>

                            </ul>
                        </li>
                    }

                    @if (_perm.See_Categories == true)
                    {
                        <li>
                            <a class="dropdown-toggle" href="@Url.Action("Index", "Category")">
                                <i class="icon-archive"></i>
                                <span class="menu-text">  Categories </span>
                                <b class="arrow js-icon-angle-down"></b>
                            </a>
                            <ul class="submenu" style="display:none;">
                                <li>
                                    <a href="@Url.Action("Index", "Category")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Manage Categories
                                    </a>
                                </li>
                                @if (_perm.Create_Categories == true)
                                {
                                    <li>
                                        <a href="@Url.Action("Create", "Category")">
                                            <i class="js-icon-double-angle-right"></i>
                                            New Categoires
                                        </a>
                                    </li>
                                }
                            </ul>
                        </li>
                    }

                    @if (_perm.See_Contents == true)
                    {
                        <li>
                            <a class="dropdown-toggle" href="@Url.Action("Index", "Contents")">
                                <i class="icon-book"></i>
                                <span class="menu-text"> Contents </span>
                                <b class="arrow js-icon-angle-down"></b>
                            </a>
                            <ul class="submenu">
                                <li>
                                    <a href="@Url.Action("Index", "Contents")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Manage Contents
                                    </a>
                                </li>
                                @if (_perm.Create_Contents == true)
                                {
                                    <li>
                                        <a href="@Url.Action("Create", "Contents")">
                                            <i class="js-icon-double-angle-right"></i>
                                            New Content
                                        </a>
                                    </li>
                                }
                                <li>
                                    <a href="@Url.Action("Index", "CustomField")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Manage CustomFields
                                    </a>
                                </li>
                            </ul>
                        </li>
                    }
                    @if (_perm.Media == true)
                    {
                        <li>
                            <a class="dropdown-toggle" href="@Url.Action("Index", "Media")">
                                <i class="icon-picture"></i>
                                <span class="menu-text"> Media Manager </span>
                            </a>
                        </li>
                    }
                    @if (_perm.Users == true)
                    {
                        <li>
                            <a class="dropdown-toggle" href="@Url.Action("Index", "User")">
                                <i class="icon-users"></i>
                                <span class="menu-text"> Users </span>
                                <b class="arrow js-icon-angle-down"></b>
                            </a>
                            <ul class="submenu">
                                <li>
                                    <a href="@Url.Action("Index", "User")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Manage User
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create", "User")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Create User
                                    </a>
                                </li>
                            </ul>
                        </li>
                    }

                    @if (_perm.Groups == true)
                    {
                        <li>
                            <a class="dropdown-toggle" href="@Url.Action("Index","Group")">
                                <i class="icon-generic"></i>
                                <span class="menu-text"> Groups </span>
                                <b class="arrow js-icon-angle-down"></b>
                            </a>
                            <ul class="submenu" style="display:none;">
                                <li>
                                    <a href="@Url.Action("Index","Group")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Manage Groups
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create","Group")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Add Groups
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Requests","Group")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Requests
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Setting","Group")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Group Setting
                                    </a>
                                </li>
                            </ul>
                        </li>
                    }

                    @if (_perm.ViewLevels == true)
                    {
                        <li>
                            <a class="dropdown-toggle" href="@Url.Action("Index", "ViewLevel")">
                                <i class="icon-eye-open"></i>
                                <span class="menu-text"> ViewLevels </span>
                                <b class="arrow js-icon-angle-down"></b>
                            </a>
                            <ul class="submenu" style="display:none;">
                                <li>
                                    <a href="@Url.Action("Index","ViewLevel")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Manage ViewLevel
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create","ViewLevel")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Add ViewLevel
                                    </a>
                                </li>
                            </ul>
                        </li>
                    }
                    @if (_perm.Languages == true)
                    {
                        <li>
                            <a class="dropdown-toggle" href="@Url.Action("Index","Languages")">
                                <i class="icon-default"></i>
                                <span class="menu-text"> Languages </span>
                                <b class="arrow js-icon-angle-down"></b>
                            </a>
                            <ul class="submenu">
                                <li>
                                    <a href="@Url.Action("Index","Languages")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Manage Language
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create","Languages")">
                                        <i class="js-icon-double-angle-right"></i>
                                        Add Languages
                                    </a>
                                </li>
                            </ul>
                        </li>
                    }
                    <li> <a href="@Url.Action("Index","Admin")"> <i class="icon-exit"></i> Close </a> </li>
                </ul>
                <div id="sidebar-collapse" class="sidebar-collapse">
                    <i class="js-icon-double-angle-left"></i>
                </div>
            </div>
            <!-- END SIDE BAR ------------------------------------------------------------------------------------>
        </div>
        <div class="main">
            @RenderBody()
        </div>
    </div>
    <div id="snackbar">Some text some message..</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/admin")
    @Scripts.Render("~/bundles/myscript")

    @RenderSection("scripts", required : false)
</body>
</html>

BBBZ/Views/Shared/_Error.cshtml
@{    
    ViewBag.Title = "Error" + ViewBag.Code;
}

<div class="container body-content">

    <br />
    <br />
    <br />
    <h2>Error <i> @ViewBag.Code </i></h2>
    <div class="col-sm-8">
        <p style="color:red">
            @ViewBag.Message
        </p>
    </div>

    <div class="col-sm-4">
        <img src="~/Content/images/robot.png" alt="error" />
    </div>
    <a href="@ViewBag.PreviousUrl" class="btn btn-sm btn-primary"> Retry </a>
    <input type="button" value="Back" class="btn btn-sm btn-info" onclick="history.go(-1);" />
</div>